#!/usr/bin/env python
from __future__ import print_function
import sys

def print_usage():
  print("usage: tsbox <create|run|destroy>")
  print("Type \"tsbox <command> --help\" to get help for a specific command.")

sys.argv.pop(0)

if not sys.argv:
  print_usage()
  sys.exit(64)
elif sys.argv[0] == "create":
  sys.argv.pop(0)
  print("C")
elif sys.argv[0] == "run":
  sys.argv.pop(0)
  print("R")
elif sys.argv[0] == "destroy":
  sys.argv.pop(0)
  print("D")
else:
  print_usage()
  sys.exit(64)