#!/usr/bin/env python
from __future__ import print_function
import sys
import yaml

def print_usage():
    print("usage: tsbox <create|run|destroy>")
    print("Type \"tsbox <command> --help\" to get help for a specific command.")


sys.argv.pop(0)

if not sys.argv:
    print_usage()
    sys.exit(64)
elif sys.argv[0] == "create":
    sys.argv.pop(0)
    if not sys.argv:
        print("wtf")
    else:
      username = sys.argv[0]
      config_file = ".tsbox/users/" + username + ".yaml"
      with open(config_file) as file:
        config = {
            'persistent': False,
            'mount': [
                '/usr/bin',
                '/usr/local/bin',
                '/lib',
                '/lib64',
                '/dev'
            ]
        }
        yaml.dump(config, file)
    print("C")
elif sys.argv[0] == "run":
    sys.argv.pop(0)
    print("R")
elif sys.argv[0] == "destroy":
    sys.argv.pop(0)
    print("D")
else:
    print_usage()
    sys.exit(64)
